name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        python -m pip install hyperon==0.2.2
        python -m pip install conan==2.5.0
        conan profile detect --force

    - name: Run Tests
      run: |
        cd ../metta-attention
        python scripts/run-tests.py